import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Suspense } from 'react';
import Loading from './loading';
import HeaderProvider from './context/HeaderContext';
import ServiceProvider from './context/ServiceContext';
import ClientProvider from './context/ClientsContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Fabio Auto Mecânica',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ServiceProvider>
        <HeaderProvider>
          <ClientProvider>
            <Suspense fallback={<Loading />}>
              <body className={inter.className}>
                {children}
              </body>
            </Suspense>
          </ClientProvider>
        </HeaderProvider>
      </ServiceProvider>
    </html>
  );
}
